version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    apt_packages:
      - pngquant
      - jpegoptim
  jobs:
    build:
      html:
        - cd doc && make setup
        - cd doc && make build
